"""Reusable utilities for DLA Lab 3."""

from .envs import make_env, observation_scale
from .config import load_lab_config, load_simple_yaml
from .experiments import (
    choose_final_temperature,
    collect_current_lunar_candidates,
    evaluate_lunar_candidates,
    evaluate_lunar_policy_configurations,
    final_lunar_evaluation,
    plot_lunar_selection,
    plot_temperature_sweep,
    print_lunar_preset_summary,
    print_training_scope,
    run_lunar_temperature_sweep,
    select_lunar_checkpoint,
    select_lunar_policy_configuration,
    train_lunar_presets,
)
from .visualization import run_cartpole_visual_episodes, run_lunar_visual_episodes, show_frames
from .a2c import (
    A2CConfig,
    A2CNet,
    A2CNetLunarSeparate,
    a2c_from_env,
    compute_gae,
    evaluate_a2c_policy,
    load_a2c_checkpoint,
    lunar_a2c_from_env,
    run_a2c_episode,
    train_a2c_single_env,
    train_a2c_vectorized,
)
from .policy_gradient import (
    PolicyNet,
    ValueNet,
    ReinforceConfig,
    Episode,
    compute_returns,
    evaluate_policy,
    policy_from_env,
    reinforce,
    reinforce_with_value_baseline,
    run_episode,
    value_from_env,
)
from .seed import set_seed

__all__ = [
    "Episode",
    "A2CConfig",
    "A2CNet",
    "A2CNetLunarSeparate",
    "PolicyNet",
    "ReinforceConfig",
    "ValueNet",
    "a2c_from_env",
    "choose_final_temperature",
    "collect_current_lunar_candidates",
    "compute_returns",
    "compute_gae",
    "evaluate_lunar_candidates",
    "evaluate_lunar_policy_configurations",
    "evaluate_a2c_policy",
    "evaluate_policy",
    "final_lunar_evaluation",
    "load_a2c_checkpoint",
    "load_lab_config",
    "load_simple_yaml",
    "lunar_a2c_from_env",
    "make_env",
    "observation_scale",
    "plot_lunar_selection",
    "plot_temperature_sweep",
    "policy_from_env",
    "print_lunar_preset_summary",
    "print_training_scope",
    "reinforce",
    "reinforce_with_value_baseline",
    "run_lunar_temperature_sweep",
    "run_cartpole_visual_episodes",
    "run_lunar_visual_episodes",
    "run_a2c_episode",
    "run_episode",
    "select_lunar_checkpoint",
    "select_lunar_policy_configuration",
    "set_seed",
    "show_frames",
    "train_lunar_presets",
    "train_a2c_single_env",
    "train_a2c_vectorized",
    "value_from_env",
]
